#!/usr/bin/env ansible-playbook
---
- name: run mezzanine from containers
  hosts: localhost
  vars:
    # The postgres container uses the same name for the database
    # and the user
    database_name: mezzanine
    database_user: mezzanine
    database_password: password
    database_port: 5432
    secret_key: randomsecretkey
    nevercache_key: randomnevercachekey
    gunicorn_port: 8000
    mezzanine_env:
      SECRET_KEY: "{{ secret_key }}"
      NEVERCACHE_KEY: "{{ nevercache_key }}"
      ALLOWED_HOSTS: "*"
      DATABASE_NAME: "{{ database_name }}"
      DATABASE_USER: "{{ database_user }}"
      DATABASE_PASSWORD: "{{ database_password }}"
      DATABASE_HOST: "{{ database_host }}"
      DATABASE_PORT: "{{ database_port }}"
      GUNICORN_PORT: "{{ gunicorn_port }}"

  tasks:
    - name: create data volume
      docker_image: path=data-volume name=lorin/mezzanine-data
    - name: start the postgres container
      docker:
        image: postgres
        publish_all_ports: True
        volumes_from: data-volume
        env:
          POSTGRES_USER: "{{ database_user }}"
          POSTGRES_PASSWORD: "{{ database_password }}"
    - set_fact: database_host={{ docker_containers[0].NetworkSettings.IPAddress }}
    - name: initialize database
      docker:
        image: lorin/mezzanine:latest
        command: python manage.py {{ item }} --noinput
        detach: False
        env: "{{ mezzanine_env }}"
      with_items:
        - syncdb
        - migrate
        - collectstatic
      register: django
    - name: run mezzanine
      docker:
        image: lorin/mezzanine:latest
        name: mezzanine
        env: "{{ mezzanine_env }}"
        publish_all_ports: True
      register: mezzanine
    - name: run nginx
      tags: nginx
      docker:
        image: nginx:latest
        publish_all_ports: True
        name: nginx
        volumes_from: mezzanine
