---
- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  sudo: True
  with_items:
    - git
    - libjpeg-dev
    - libpq-dev
    - python-dev
    - python-pip
    - python-psycopg2
    - python-setuptools
- include: django.yml
